<?php

use app\helpers\Helpers;

Helpers::header($data) ?>

<style>
    .hellow {
        color: #8E44AD;
        text-align: center;
        font-size: 50px;
        font-weight: bold;
        font-family: 'Times New Roman', Times, serif;
        margin-top: 20px;
        margin-bottom: 20px;
        margin-left: 20px;
        margin-right: 20px;
    }
</style>
<h1 class="hellow"><?= $content ?></h1>
<?php
Helpers::footer() ?>