<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?=BASE_URL?>/resources/assets/css/index.css">
    <link rel="shortcut icon" href="<?=BASE_URL?>/resources/assets/images/logo_ini.png" type="image/x-icon">
    <title>Gestión Docentes | <?=$data['page']??''?></title>
</head>
<body>
<nav class="nav">
    <h2 class="nav_logo"><a class="nav_items" href="https://ebercode.com/" target="_blank">EberCode</a></h2>
    <ul class="nav_menu">
        <li class="nav_link"><a class="nav_items btn_donar" href="https://www.paypal.me/detoditoeber23"  target="_blank">Donar 😘</a></li>
    </ul>
</nav>
<main class="main">

